use * from types

type data = list<u8>

resource cloudevent {
    static create: function() -> cloudevent
    set-id: function(id: string)
    get-id: function() -> string
    set-source: function(source: string)
    get-source: function() -> string
    set-specversion: function(specversion: string)
    get-specversion: function() -> string
    %set-type: function(%type: string)
    %get-type: function() -> string
    set-data: function(data: data)
    get-data: function() -> data
    set-datacontenttype: function(datacontenttype: string)
    get-datacontenttype: function() -> string
    set-dataschema: function(dataschema: string)
    get-dataschema: function() -> string
    set-subject: function(subject: string)
    get-subject: function() -> string
    set-time: function(time: string)
    get-time: function() -> string
}

ce-handler: function(event: cloudevent) -> expected<cloudevent, error>
