
use * from types

type document = list<u8> 

// Create operations

// Create a new collection in the database
create-collection: function(db: string, name: string) -> expected<_, error>

// Insert a document into a collection 
insert-one-document: function(db: string, collection: string, id: string, doc: document) -> expected<string, error>

// Read operations

// Get a document from the collection by name
find-document: function(db: string, collection: string, name: string) -> expected<document, error>

// Delete operations

// Drop the database
drop-database: function(db: string) -> expected<_, error>